name: Test ARC Runner

on: workflow_dispatch

jobs:
  test:
    runs-on: arc-runners   # это метка, которую использует runner scale set
    steps:
      - run: echo "Hello from ARC runner inside k8s"
